### ISSUE TITLE
Add License file

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/Auto-Compression#1]
This repository has no license file.

If you extend TVM to implement Latency Predictor, you must specify your license referring to TVM's license.

[TVM seems to use "BSD 3-Clause" License.](https://github.com/Tencent/PocketFlow/blob/master/LICENSE.TXT)

I think that "BSD 3-Clause" license is proper for this repository.

**Comment by hoseung2** [comment]
Updated.
