### ISSUE TITLE
 Is it okay to increase the number of candidate pruning rate?

### ISSUE THREAD

**Issue by minusjet** [SKKU-ESLAB/Auto-Compression#16]
There are too limited pruning ratio options in the code.

I want to search more accurate model with more search space.

How about increasing the number of candidate to 10 or 20?

**Comment by GH-Jo** [comment]
I think the only problem is training time when you increase the number of candidates up to 10 or somewhat more. 

If you increase it to more than 20, the vast amount of parameters will hinder the learning, so it will be difficult for you to know if the selection is adequate.
